//EnterBooks.php
&lt;!DOCTYPE HTML&gt;
&lt;html&gt;
&lt;body bgcolor=&quot;87ceeb&quot;&gt;
&lt;center&gt;&lt;h2&gt;Simple Library Management System&lt;/h2&gt;&lt;/center&gt;
&lt;!--Once the form is submitted, all the form data is forwarded to InsertBooks.php --&gt;
&lt;form action=&quot;InsertBooks.php&quot; method=&quot;post&quot;&gt;

&lt;table border=&quot;2&quot; align=&quot;center&quot; cellpadding=&quot;5&quot; cellspacing=&quot;5&quot;&gt;
&lt;tr&gt;
&lt;td&gt; Enter ISBN :&lt;/td&gt;
&lt;td&gt; &lt;input type=&quot;text&quot; name=&quot;isbn&quot; size=&quot;48&quot;&gt; &lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt; Enter Title :&lt;/td&gt;
&lt;td&gt; &lt;input type=&quot;text&quot; name=&quot;title&quot; size=&quot;48&quot;&gt; &lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt; Enter Author :&lt;/td&gt;
&lt;td&gt; &lt;input type=&quot;text&quot; name=&quot;author&quot; size=&quot;48&quot;&gt; &lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;

&lt;td&gt; Enter Edition :&lt;/td&gt;
&lt;td&gt; &lt;input type=&quot;text&quot; name=&quot;edition&quot; size=&quot;48&quot;&gt; &lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt; Enter Publication: &lt;/td&gt;
&lt;td&gt; &lt;input type=&quot;text&quot; name=&quot;publication&quot; size=&quot;48&quot;&gt; &lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;/td&gt;
&lt;td&gt;
&lt;input type=&quot;submit&quot; value=&quot;submit&quot;&gt;
&lt;input type=&quot;reset&quot; value=&quot;Reset&quot;&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/table&gt;
&lt;/form&gt;
&lt;/body&gt;
&lt;/html&gt;